# Generated by Django 2.2.16 on 2022-08-25 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата публикации комментария', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
